services:
  openfhir-hapi-interceptor-hapi:
    build: .
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./application.yml:/app/config/application.yml:ro
      - ./cdrs.yml:/etc/cdrs.yml
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      openfhir-hapi-interceptor-ehrbase-postgres:
        condition: service_healthy

  openfhir-hapi-interceptor-ehrbase:
    image: ehrbase/ehrbase
    depends_on:
      - openfhir-hapi-interceptor-ehrbase-postgres
    ports:
      - 8082:8080
    environment:
      - SECURITY_AUTHTYPE=BASIC
      - DB_URL=jdbc:postgresql://openfhir-hapi-interceptor-ehrbase-postgres:5432/ehrbase
      - DB_USER=ehrbase_restricted
      - DB_PASS=ehrbase_restricted
      - DB_USER_ADMIN=ehrbase
      - DB_PASS_ADMIN=ehrbase
      - SERVER_NODENAME=local.ehrbase.org
      - SPRING_PROFILES_ACTIVE=local

  openfhir-hapi-interceptor-ehrbase-postgres:
    container_name: openfhir-hapi-interceptor-ehrbase-postgres
    image: ehrbase/ehrbase-v2-postgres:16.2
    ports:
      - 5439:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - EHRBASE_USER=ehrbase_restricted
      - EHRBASE_PASSWORD=ehrbase_restricted
      - EHRBASE_USER_ADMIN=ehrbase
      - EHRBASE_PASSWORD_ADMIN=ehrbase
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/02-hapi.sql:ro
      - openfhir-hapi-interceptor-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  openfhir-hapi-interceptor-db-data:
