@startuml fhir_store

actor "FHIR Consumer/Source" as consumer

box "HAPI Integration Layer"
    participant "openFHIR HAPI Interceptor***REMOVED***n(this project)" as facade
    participant "HAPI FHIR DB" as hapi

end box

participant "openFHIR" as openfhir
participant "openEHR CDR" as cdr

consumer -> facade : Store FHIR Resource

facade -> hapi : PIX lookup — read Patient,***REMOVED***nfind EHR ID for target CDR

alt EHR ID not found
    facade -> cdr : POST /ehr (create new EHR)
    cdr --> facade : ehrId
    facade -> hapi : update Patient with new ehrId identifier
end

facade -> openfhir : REST /toopenehr (FHIR resource)

openfhir --> facade : openEHR Composition

facade -> cdr : POST /ehr/{{ehrId}}/composition

@enduml
